services:
  justrecit:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 5173:5173
    environment:
      - CLIENT_SECRET=${CLIENT_SECRET}
      - CLIENT_ID=${CLIENT_ID}
      - API_KEY=${API_KEY}
      - AUTH_DOMAIN=${AUTH_DOMAIN}
      - PROJECT_ID=${PROJECT_ID}
      - STORAGE_BUCKET=${STORAGE_BUCKET}
      - MESSAGING_SENDER_ID=${MESSAGING_SENDER_ID}
      - APP_ID=${APP_ID}
    container_name: justrecit-production

  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - justrecit
    container_name: justrecit-nginx
